language: generic

services:
  - docker

branches:
  only:
    - master
    - /[0-9]+\.[0-9]+\.[0-9]+/

env:
  global:
    - APP_NAME=flask-slack-app-template

before_install:
  - wget https://hearst-hatchery.github.io/atlas/v3/vault.sh;
  - chmod +x vault.sh;
  - source vault.sh;

install:
  - docker pull quay.io/hearst/${APP_NAME}:${TRAVIS_COMMIT:0:7} || docker build -t quay.io/hearst/${APP_NAME}:${TRAVIS_COMMIT:0:7} .

script:
  - /bin/true

after_success: >-
  if [ "$TRAVIS_PULL_REQUEST" != "false" ];then
    wget https://hearst-hatchery.github.io/atlas/v2/deploy_pull_request.sh;
    chmod +x deploy_pull_request.sh;
    ./deploy_pull_request.sh "${APP_NAME}" ${TRAVIS_PULL_REQUEST} ${TRAVIS_COMMIT:0:7};
  fi;

deploy:
  - provider: script
    script: >-
      wget https://hearst-hatchery.github.io/atlas/v2/deploy_master.sh;
      chmod +x deploy_master.sh;
      ./deploy_master.sh;
    on:
      branch: master
  - provider: script
    script: >-
      wget https://hearst-hatchery.github.io/atlas/v2/deploy_semver.sh;
      chmod +x deploy_semver.sh;
      ./deploy_semver.sh;
      wget https://hearst-hatchery.github.io/atlas/v2/auto_deploy.sh;
      chmod +x auto_deploy.sh;
      ./auto_deploy.sh "${APP_NAME}" ${TRAVIS_TAG} kubefeature;
    on:
      tags: true
      condition: $TRAVIS_TAG =~ [0-9]+\.[0-9]+\.[0-9]+
