kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: flask-slack-app-template
  name: flask-slack-app-template
  namespace: default
spec:
  replicas: {{ k8s_replicas }}
  selector:
    matchLabels:
      app: flask-slack-app-template
  revisionHistoryLimit: 5
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flask-slack-app-template
    spec:
      volumes: null
      containers:
      - name: flask-slack-app-template
        image: quay.io/hearst/flask-slack-app-template:{{ tag }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: '{{ k8s_cpu_requests }}'
            memory: '{{ k8s_memory_requests }}'
        env:
        - name: SLACKBOT_REPLYBOT_TOKEN
          value: '{{ slackbot_replybot_token }}'
        - name: SLACK_SIGNING_SECRET
          value: '{{ slack_signing_secret }}'
        - name: LOG_LEVEL
          value: '{{ log_level }}'
        ports:
        - containerPort: 80
          protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
      imagePullSecrets:
      - name: quay.io
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      dnsPolicy: ClusterFirst
