kind: Service
apiVersion: v1
metadata:
  labels:
    app: flask-slack-app-template
  name: flask-slack-app-template
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: flask-slack-app-template
